server:
  port: 9991

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_jwt?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

logging:
  level:
    com.example: info
    org.springframework: info

# JWT
jwt:
  header: "Authorization"
  secret: "mySecret"
  expiration: 604800 # 7days 单位 s
  tokenHead: "Bearer "
